export default function () {
  return {
    pipe: ' | ',
    routeVia: 'Route via ',
    navHome: 'Home',
    navProgram: 'Program',
    navQA: 'Q & A',
    navRegistry: 'Registry',
    RSVPButtonNo: 'No, I’m not attending',
    RSVPButtonNoCorrection: 'No, I’ve changed my mind',
    RSVPButtonYes: 'Yes, I’m attending',
    RSVPButtonYesCorrection: 'I’ve changed my mind!',
    noRSVPTitle: 'You’ll be missed!',
    noRSVPBody: 'But seriously, thanks for letting us know.',
    QATitle: 'Q <span class="text--tinted--tertiary">&</span> A',
    registryTitle: 'Registry',
    programTitle: '<span class="text--tinted--tertiary ">0</span><span class="text--tinted--primary">1</span><span class="text--tinted--tertiary ">.</span><span class="text--tinted--primary">11</span><span class="text--tinted--tertiary ">.</span><span class="text--tinted--primary">25</span>',
    receptionAddress: '445 E. Morrow St, Georgetown, Texas',
    numbers: ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'],
    continue: 'Continue',
    confirm: 'Confirm',
    submit: 'Submit',
    yes: 'Yes',
    no: 'No',
    attendee: 'attendee',
    contact: 'Contact',
    name: 'Name',
    meal: 'Meal'
  }
}
